[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openai-agent-sdk-factory"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiolimiter>=1.2.1",
    "omegaconf>=2.3.0",
    "openai-agents>=0.3.3",
    "python-dotenv>=1.1.1",
    "tiktoken>=0.12.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["agent_factory*"]   # 打包 agent_factory 及其子套件